format_version: 10
pipelines:
  hello:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-e5b11b0:
        git: https://github.com/benbenbenbenbenben/tree-sitter-javascript
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - foo:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          task0:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - i
                command: npm
                run_if: passed
            - exec:
                arguments:
                - t
                command: npm
                run_if: passed
